blank_issues_enabled: true
contact_links:
  - name: System Documentation
    url: https://r4ppz.github.io/research-repo-docs/
    about: Read the docs/specs first. Especially if you want to contribute or ask about project architecture.
