#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

changed_files="$(git diff-tree -r --name-only --no-commit-id ORIG_HEAD HEAD)"

if echo "$changed_files" | grep --quiet "package-lock.json"; then
  echo "Dependencies changed. Running npm install..."
  npm install
fi
